//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapMedicial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Doctor_ID { get; set; }
        public string Description { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
